version: '3.8'

services:
  backend:
    build: ./backend
    container_name: eticaret-backend
    
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: eticaret-frontend
    
    ports:
      - "8080:3000"
    depends_on:
      - backend
    
  redis:
    image: redis:latest
    container_name: redis
    
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    container_name: mongo
    
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
